# Generated by Django 4.1.3 on 2022-12-20 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=200)),
                ('Course_fees', models.FloatField(max_length=50)),
                ('Course_duration', models.CharField(max_length=200)),
                ('Course_textbox', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_name', models.CharField(max_length=200)),
                ('Teacher_email', models.CharField(max_length=200)),
                ('Teacher_mobile_number', models.IntegerField(max_length=10)),
                ('Teacher_joining_date', models.DateField()),
                ('Teacher_education', models.CharField(max_length=100)),
                ('Teacher_employee_id', models.IntegerField(max_length=10)),
                ('Teacher_work_exp', models.CharField(max_length=200)),
                ('teacher_pack', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Password', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=200)),
                ('Student_email', models.EmailField(max_length=200)),
                ('Student_mobile_number', models.IntegerField(max_length=10)),
                ('Student_college', models.CharField(max_length=200)),
                ('Student_degree', models.CharField(max_length=200)),
                ('Student_due', models.IntegerField()),
                ('Student_paid', models.IntegerField()),
                ('Student_total', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('Course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
            ],
        ),
    ]
